config/routes.rb
Rails.application.routes.draw do
  resources :news do
    collection do
      get :sync
    end
  end
  resources :articles
  devise_for :users

  resources :attachments do
    member do
      get :download
    end
    collection do
      post :upload
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	mount_uploader :file, FileUploader

	def file_name
		CGI.unescape(File.basename(file.url))
	end
end

app/controllers/attachments_controller.rb
include ActionView::Helpers::NumberHelper
class AttachmentsController < ApplicationController
  def index
    @attachments = Attachment.all
  end

  def download
    attachment = Attachment.find(params[:id])
    file = File.open("public" + CGI.unescape(attachment.file.url))
    send_file file
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
    redirect_to attachments_path, notice: '删除成功'
  end

  def upload
    attachment = Attachment.new
    if params[:attachment].present?
      attachment.file = params[:attachment][:file]
      if attachment.save
        redirect_to attachments_path, notice: '上传成功!'
      else
        redirect_to attachments_path, alert: '上传失败'
      end
    else
      redirect_to attachments_path, alert: '请先选择文件！'
    end
  end
end

app/views/attachments/index.html.haml
.row.m-t-sm
  .col-lg-12
  = form_for Attachment.new, url: upload_attachments_path, method: :post, html: { multipart: true, id: "fileupload" } do |f|
    .row.fileupload-buttonbar
      .col-lg-7
        .btn.btn-primary.fileinput-button
          %i.glyphicon.glyphicon-plus
          选择或拖拽文件
          = f.file_field :file
          = f.submit "上传"
    .tabs-container
      .tab-content
        .tab-pane#public_files.active
          .panel-body
            共有
            %strong=@attachments.count
            个结果
            %table.footable.table.table-stripped.toggle-arrow-tiny{"data-page-size" => "15"}
              %thead
                %tr
                  %th 文件名称
                  %th 大小
                  %th.text-right 操作
              %tbody
                - @attachments.each_with_index do |attachment, index|
                  %tr
                    %td=attachment.file_name
                    %td=number_to_human_size attachment.file.size
                    %td.text-right
                      = link_to '下载', attachment.file.url, class: "btn btn-warning btn-xs", target: "_blank"
                      = link_to '删除', attachment_path(attachment), method: :delete,
                          data: { :confirm => '确定要删除吗?' }, class: "btn btn-danger btn-xs"
              %tfoot
                %tr
                  %td.footable-visible{:colspan => "9"}
                    %ul.pagination.pull-right