config/routes.rb
Rails.application.routes.draw do
  resources :news do
    collection do
      get :sync
    end
  end
  resources :articles
  devise_for :users

  resources :attachments do
    member do
      get :download
    end
    collection do
      post :upload
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ActiveRecord::Base
  TENCENT_SYNC_URL = 'https://pacaio.match.qq.com/irs/rcd'
  TOUTIAO_SYNC_URL = 'https://www.toutiao.com/api/pc/feed/?'
  validates_uniqueness_of :item_id
  class << self
    # 腾讯新闻同步
    def sync_tencent
      query_params = {
          cid: 4,
          token: '9513f1a78a663e1d25b46a826f248c3c',
          page: 0,
      }.with_indifferent_access
      result = RestClient.get(TENCENT_SYNC_URL, params: query_params)
      res_body = result.body
      # res_body[-1] = ''
      # res_body.gsub!(/^__jp\d/, '')
      # res_body[0] = ''
      res_hash = JSON.parse(res_body)
      puts "page: #{query_params[:page]}"
      while(res_hash["datanum"] != 0)
        res_hash['data'].each do |item|
          news = News.new
          News.column_names.reject{|c| c == 'id'}.each do |col_name|
            news.assign_attributes("#{col_name}": item[col_name])
          end
          news.assign_attributes("t_id": item['id'])
          news.save!
        rescue => e
          puts "处理出错: #{e.message}"
        end
        query_params[:page] += 1
        result = RestClient.get(TENCENT_SYNC_URL, params: query_params)
        res_body = result.body
        # res_body[-1] = ''
        # res_body.gsub!(/^__jp\d/, '')
        # res_body[0] = ''
        res_hash = JSON.parse(res_body)
      end
      puts "page: #{query_params[:page]} complete!"
    end

    # 头条新闻同步
    def sync_toutiao
      query_params = {
          max_behot_time: Time.now.beginning_of_day.to_i,
          category: 'news_tech',
          utm_source: 'toutiao',
          widen: 1,
          tadrequire: true
      }.with_indifferent_access
      result = RestClient.get(TOUTIAO_SYNC_URL + query_params.to_query, cookies: {:tt_webid=> '6662903737592251908'})
      res_hash = JSON.parse(result.body)
      puts "开始同步"
      number = 0
      while(res_hash['data'].present?)
        res_hash['data'].each do |item|
          news = News.new
          news.title= item['title']
          news.item_id= item['item_id']
          news.group_id= item['group_id']
          news.abstract= item['abstract']
          news.comments_count= item['comments_count']
          news.chinese_tag= item['chinese_tag']
          news.source= item['source']
          news.source_url= 'https://www.toutiao.com' + item['source_url']
          news.middle_image_url= item['middle_image']
          news.save!
          puts "已处理:#{number}条新闻!"
          number+=1
        rescue ActiveRecord::RecordInvalid=> e
          puts "同一文章,item_id重复了:#{e.message}"
        end
        query_params[:max_behot_time]= res_hash['next']['max_behot_time']
        result = RestClient.get(TOUTIAO_SYNC_URL + query_params.to_query, cookies: {:tt_webid=> '6662903737592251908'})
        puts "该批次爬取结束:#{query_params.to_query}"
        res_hash = JSON.parse(result.body)
      end
      puts '结束：以下是res_hash'
      puts res_hash
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.where("created_at > ? and created_at < ?", Time.now.beginning_of_day, Time.now.end_of_day).order("comments_count desc").limit(100)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sync
    News.sync_toutiao
    redirect_to news_index_path, notice: '同步完成'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :t_id, :app_id, :avatar_url, :v_url, :view_count, :update_time, :comment_num)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.haml
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      %ul
        - @news.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :t_id
    = f.text_field :t_id
  .field
    = f.label :app_id
    = f.text_field :app_id
  .field
    = f.label :avatar_url
    = f.text_area :avatar_url
  .field
    = f.label :v_url
    = f.text_field :v_url
  .field
    = f.label :view_count
    = f.number_field :view_count
  .field
    = f.label :update_time
    = f.datetime_select :update_time
  .field
    = f.label :comment_num
    = f.number_field :comment_num
  .actions
    = f.submit 'Save'

app/views/news/edit.html.haml
%h1 Editing news

= render 'form'

= link_to 'Show', @news
\|
= link_to 'Back', news_index_path

app/views/news/index.html.haml
%h1 Listing news
= News.count
= link_to '开始同步', sync_news_index_path, class: 'btn btn-primary'
%table.table
  %thead
    %tr
      %th 标题
      %th 封面
      %th 评论数
      %th 摘要
      %th item_id
      %th group_id
      %th source_url
      %th 更新时间

  %tbody
    - @news.each do |news|
      %tr
        %td= news.title
        %td= image_tag news.middle_image_url if news.middle_image_url.present?
        %td= news.comments_count
        %td= news.abstract
        %td= news.item_id
        %td= news.group_id
        %td= link_to news.source_url, news.source_url
        %td= news.updated_at
%br

= link_to 'New News', new_news_path

app/views/news/new.html.haml
%h1 New news

= render 'form'

= link_to 'Back', news_index_path

app/views/news/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @news.title
%p
  %b T:
  = @news.t_id
%p
  %b App:
  = @news.app_id
%p
  %b Avatar url:
  = @news.avatar_url
%p
  %b V url:
  = @news.v_url
%p
  %b View count:
  = @news.view_count
%p
  %b Update time:
  = @news.update_time
%p
  %b Comment num:
  = @news.comment_num

= link_to 'Edit', edit_news_path(@news)
\|
= link_to 'Back', news_index_path